version: "3"

services:
  php:
    build:
      dockerfile: Dockerfile.php
    volumes:
      - /app/vendor
      - ./php:/app
    environment:
      TZ: Asia/Tokyo

  node:
    build:
      dockerfile: Dockerfile.node
    volumes:
      - "/usr/src/app/node_modules"
      - ./node:/usr/src/app
    environment:
      TZ: Asia/Tokyo

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "10443:443"

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword

  mysql:
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
